---
language: php
os:
  - linux
sudo: false
php:
  - 7.2
  - 7.3
  - 7.4
  - nightly
matrix:
  allow_failures:
    - php: nightly
services:
  - mysql
before_script:
  - cp etc/config.sample.json etc/config.phoenix.json
script:
  - bash -c 'set -e;for file in $(find . -type f -regextype posix-extended
    -regex .*\.\(php\|dm\) -print); do php -e -l -f "$file"; done'
